const PAYMENT_METHODS = ["COD", "BANK_TRANSFER", "MOMO", "VNPAY", "CREDIT_CARD"];
const PAYMENT_STATUSES = ["PENDING", "SUCCESS", "FAILED", "REFUNDED"];

module.exports = {
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
};
