const PAYMENT_METHOD = {
  COD: "COD",
  BANK_TRANSFER: "BANK_TRANSFER",
  MOMO: "MOMO",
  VNPAY: "VNPAY",
  CREDIT_CARD: "CREDIT_CARD",
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

const PAYMENT_METHODS = Object.values(PAYMENT_METHOD);
const PAYMENT_STATUSES = Object.values(PAYMENT_STATUS);

module.exports = {
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
};
